// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSystem.Data;

#nullable disable

namespace SchoolSystem.Migrations
{
    [DbContext(typeof(SystemSchoolDbContext))]
    [Migration("20260818081852_AddDirectorates")]
    partial class AddDirectorates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .IsFixedLength();

                    b.Property<DateOnly?>("DateAndTime")
                        .HasColumnType("date");

                    b.Property<string>("Excuse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdClass")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLectuer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTeacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeletedAttendance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedLectuer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedTeacher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromLectuer")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Attendan__3213E83FAD8350D2");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdLectuer");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdTeacher");

                    b.HasIndex(new[] { "IdSchool" }, "IX_Attendance_IdSchool");

                    b.HasIndex(new[] { "IdSchool", "IdTeacher" }, "IX_Attendance_IdSchool_IdTeacher");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Branch__54205B04058BBB4F");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Directorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Directorate", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.DirectorateManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DirectorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex("DirectorateId")
                        .IsUnique();

                    b.ToTable("DirectorateManager", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ErrorLog__3214EC07A2529995");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("SchoolSystem.Data.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TheType")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id")
                        .HasName("PK__Gender__3214EC070A22819D");

                    b.ToTable("Gender", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Grade", b =>
                {
                    b.Property<Guid>("GradesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GradesID");

                    b.Property<int?>("Activity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Final")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("FirstMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("IdClass")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLectuer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTeacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeletedClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedGrades")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedLectuer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedTeacher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromLectuer")
                        .HasColumnType("bit");

                    b.Property<int?>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SecondMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(((([FirstMonth]+[Mid])+[SecondMonth])+[Activity])+[Final])", false);

                    b.HasKey("GradesId")
                        .HasName("PK__Grades__931A40BF88D8CDCA");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdLectuer");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdTeacher");

                    b.HasIndex(new[] { "GradesId" }, "IX_Grades_Id");

                    b.HasIndex(new[] { "IdSchool" }, "IX_Grades_IdSchool");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolSystem.Data.Lectuer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Lectuer__3213E83FBA6843F5");

                    b.HasIndex(new[] { "IdSchool" }, "IX_Lectuer_IdSchool");

                    b.HasIndex(new[] { "Name" }, "IX_Lectuer_Name");

                    b.ToTable("Lectuer", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Menegar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("TheDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Menegar__3213E83FE96BFA1F");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex(new[] { "IdSchool" }, "IX_Menegar_IdSchool");

                    b.HasIndex(new[] { "Name" }, "IX_Menegar_Name");

                    b.HasIndex(new[] { "IdNumber" }, "UQ_Menegar_IdNumber")
                        .IsUnique()
                        .HasFilter("[IdNumber] IS NOT NULL");

                    b.ToTable("Menegar", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.ProfileImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ProfileI__3214EC07AD185F4E");

                    b.ToTable("ProfileImage", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DirectorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdGender")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStatusSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxClass")
                        .HasColumnType("int");

                    b.Property<int?>("MinClass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__School__3214EC07F11AFDBA");

                    b.HasIndex("DirectorateId");

                    b.HasIndex("IdGender");

                    b.HasIndex("IdStage");

                    b.HasIndex("IdStatusSchool");

                    b.ToTable("School", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.StageClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("MaxClass")
                        .HasColumnType("int");

                    b.Property<int>("MinClass")
                        .HasColumnType("int");

                    b.Property<string>("NameStage")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__StageCla__3214EC07B7F14D02");

                    b.HasIndex(new[] { "Code" }, "UQ__StageCla__A25C5AA7AAECF2F1")
                        .IsUnique();

                    b.ToTable("StageClass", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.StatusSchool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Condition")
                        .HasColumnType("bit")
                        .HasColumnName("condition");

                    b.Property<string>("TheType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__StatusSc__3214EC073DB2CBA3");

                    b.ToTable("StatusSchool", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("IdClass")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeletedClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedStudent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("TheDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Student__3213E83F6F20DDDC");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex("IdClass");

                    b.HasIndex(new[] { "IdSchool" }, "IX_Student_IdSchool");

                    b.HasIndex(new[] { "Name" }, "IX_Student_Name");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.StudentLectuerTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdClass")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLectuer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStudent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTeacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeletedClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedLectuer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedStudent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedStudentLectuerTeacher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedTeacher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromLectuer")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__StudentL__3213E83F373E3AFF");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdLectuer");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdTeacher");

                    b.HasIndex(new[] { "IdSchool" }, "IX_StudentLectuer_IdSchool");

                    b.ToTable("StudentLectuerTeacher", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("IdNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("TheDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Teacher__3213E83F92AB32EF");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex(new[] { "IdSchool" }, "IX_Teacher_IdSchool");

                    b.HasIndex(new[] { "Name" }, "IX_Teacher_Name");

                    b.HasIndex(new[] { "IdNumber" }, "UQ_Teacher_IdNumber")
                        .IsUnique()
                        .HasFilter("[IdNumber] IS NOT NULL");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.TeacherLectuerClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdClass")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLectuer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTeacher")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeletedClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedLectuer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedTeacher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedTeacherLectuerClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromClass")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTeacherRemovedFromLectuer")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__TeacherL__3213E83F5B2FD59A");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdLectuer");

                    b.HasIndex("IdTeacher");

                    b.HasIndex(new[] { "IdSchool" }, "IX_TeacherLectuer_IdSchool");

                    b.ToTable("TeacherLectuerClass", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Data.TheClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("IdBranch")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdStage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletedSchool")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("NumberClass")
                        .HasColumnType("int");

                    b.Property<int?>("Section")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TheClass__3213E83FD60CD186");

                    b.HasIndex("IdBranch");

                    b.HasIndex("IdStage");

                    b.HasIndex(new[] { "IdSchool" }, "IX_TheClass_IdSchool");

                    b.ToTable("TheClass", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolSystem.Data.Attendance", b =>
                {
                    b.HasOne("SchoolSystem.Data.TheClass", "IdClassNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("IdClass")
                        .HasConstraintName("FK_Attendance_TheClass");

                    b.HasOne("SchoolSystem.Data.Lectuer", "IdLectuerNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("IdLectuer")
                        .HasConstraintName("FK_Attendance_Lectuer");

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK_Attendance_School");

                    b.HasOne("SchoolSystem.Data.Student", "IdStudentNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("IdStudent")
                        .HasConstraintName("FK_Attendance_Student");

                    b.HasOne("SchoolSystem.Data.Teacher", "IdTeacherNavigation")
                        .WithMany("Attendances")
                        .HasForeignKey("IdTeacher")
                        .HasConstraintName("FK_Attendance_Teacher");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdLectuerNavigation");

                    b.Navigation("IdSchoolNavigation");

                    b.Navigation("IdStudentNavigation");

                    b.Navigation("IdTeacherNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.DirectorateManager", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", "ApplicationUser")
                        .WithOne("DirectorateManager")
                        .HasForeignKey("SchoolSystem.Data.DirectorateManager", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSystem.Data.Directorate", "Directorate")
                        .WithOne("Manager")
                        .HasForeignKey("SchoolSystem.Data.DirectorateManager", "DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Directorate");
                });

            modelBuilder.Entity("SchoolSystem.Data.Grade", b =>
                {
                    b.HasOne("SchoolSystem.Data.TheClass", "IdClassNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("IdClass")
                        .HasConstraintName("FK__Grades__IdClass__0D0FEE32");

                    b.HasOne("SchoolSystem.Data.Lectuer", "IdLectuerNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("IdLectuer")
                        .HasConstraintName("FK_Grades_Lectuer");

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK__Grades__IdSchool__6D6238AF");

                    b.HasOne("SchoolSystem.Data.Student", "IdStudentNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("IdStudent")
                        .HasConstraintName("FK_Grades_Student");

                    b.HasOne("SchoolSystem.Data.Teacher", "IdTeacherNavigation")
                        .WithMany("Grades")
                        .HasForeignKey("IdTeacher")
                        .HasConstraintName("FK_Grades_Teacher");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdLectuerNavigation");

                    b.Navigation("IdSchoolNavigation");

                    b.Navigation("IdStudentNavigation");

                    b.Navigation("IdTeacherNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.Lectuer", b =>
                {
                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("Lectuers")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK__Lectuer__IdSchoo__6C6E1476");

                    b.Navigation("IdSchoolNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.Menegar", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", "ApplicationUser")
                        .WithOne("Menegar")
                        .HasForeignKey("SchoolSystem.Data.Menegar", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("Menegars")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK__Menegar__IdSchoo__23F3538A");

                    b.Navigation("ApplicationUser");

                    b.Navigation("IdSchoolNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.School", b =>
                {
                    b.HasOne("SchoolSystem.Data.Directorate", "Directorate")
                        .WithMany("Schools")
                        .HasForeignKey("DirectorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Data.Gender", "IdGenderNavigation")
                        .WithMany("Schools")
                        .HasForeignKey("IdGender")
                        .HasConstraintName("FK__School__IdGender__28B808A7");

                    b.HasOne("SchoolSystem.Data.StageClass", "IdStageNavigation")
                        .WithMany("Schools")
                        .HasForeignKey("IdStage")
                        .HasConstraintName("FK__School__IdStage__377B294A");

                    b.HasOne("SchoolSystem.Data.StatusSchool", "IdStatusSchoolNavigation")
                        .WithMany("Schools")
                        .HasForeignKey("IdStatusSchool")
                        .HasConstraintName("FK__School__IdStatus__22FF2F51");

                    b.Navigation("Directorate");

                    b.Navigation("IdGenderNavigation");

                    b.Navigation("IdStageNavigation");

                    b.Navigation("IdStatusSchoolNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.Student", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", "ApplicationUser")
                        .WithOne("Student")
                        .HasForeignKey("SchoolSystem.Data.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSystem.Data.TheClass", "IdClassNavigation")
                        .WithMany("Students")
                        .HasForeignKey("IdClass")
                        .HasConstraintName("FK__Student__IdClass__1A1FD08D");

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("Students")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK__Student__IdSchoo__24E777C3");

                    b.Navigation("ApplicationUser");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdSchoolNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.StudentLectuerTeacher", b =>
                {
                    b.HasOne("SchoolSystem.Data.TheClass", "IdClassNavigation")
                        .WithMany("StudentLectuerTeachers")
                        .HasForeignKey("IdClass")
                        .HasConstraintName("FK__StudentLe__IdCla__08F5448B");

                    b.HasOne("SchoolSystem.Data.Lectuer", "IdLectuerNavigation")
                        .WithMany("StudentLectuerTeachers")
                        .HasForeignKey("IdLectuer")
                        .HasConstraintName("FK_StudentLectuer_Lectuer");

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("StudentLectuerTeachers")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK_StudentLectuer_School");

                    b.HasOne("SchoolSystem.Data.Student", "IdStudentNavigation")
                        .WithMany("StudentLectuerTeachers")
                        .HasForeignKey("IdStudent")
                        .HasConstraintName("FK_StudentLectuer_Student");

                    b.HasOne("SchoolSystem.Data.Teacher", "IdTeacherNavigation")
                        .WithMany("StudentLectuerTeachers")
                        .HasForeignKey("IdTeacher")
                        .HasConstraintName("FK__StudentLe__IdTea__09E968C4");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdLectuerNavigation");

                    b.Navigation("IdSchoolNavigation");

                    b.Navigation("IdStudentNavigation");

                    b.Navigation("IdTeacherNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.Teacher", b =>
                {
                    b.HasOne("SchoolSystem.Data.ApplicationUser", "ApplicationUser")
                        .WithOne("Teacher")
                        .HasForeignKey("SchoolSystem.Data.Teacher", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("Teachers")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK__Teacher__IdSchoo__25DB9BFC");

                    b.Navigation("ApplicationUser");

                    b.Navigation("IdSchoolNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.TeacherLectuerClass", b =>
                {
                    b.HasOne("SchoolSystem.Data.TheClass", "IdClassNavigation")
                        .WithMany("TeacherLectuerClasses")
                        .HasForeignKey("IdClass")
                        .HasConstraintName("FK__TeacherLe__IdCla__74EE4BDE");

                    b.HasOne("SchoolSystem.Data.Lectuer", "IdLectuerNavigation")
                        .WithMany("TeacherLectuerClasses")
                        .HasForeignKey("IdLectuer")
                        .HasConstraintName("FK_TeacherLectuer_Lectuer");

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("TeacherLectuerClasses")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK__TeacherLe__IdSch__7D2E8C24");

                    b.HasOne("SchoolSystem.Data.Teacher", "IdTeacherNavigation")
                        .WithMany("TeacherLectuerClasses")
                        .HasForeignKey("IdTeacher")
                        .HasConstraintName("FK_TeacherLectuer_Teacher");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdLectuerNavigation");

                    b.Navigation("IdSchoolNavigation");

                    b.Navigation("IdTeacherNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.TheClass", b =>
                {
                    b.HasOne("SchoolSystem.Data.Branch", "IdBranchNavigation")
                        .WithMany("TheClasses")
                        .HasForeignKey("IdBranch")
                        .HasConstraintName("FK__TheClass__IdBran__3592E0D8");

                    b.HasOne("SchoolSystem.Data.School", "IdSchoolNavigation")
                        .WithMany("TheClasses")
                        .HasForeignKey("IdSchool")
                        .HasConstraintName("FK_TheClass_School");

                    b.HasOne("SchoolSystem.Data.StageClass", "IdStageNavigation")
                        .WithMany("TheClasses")
                        .HasForeignKey("IdStage")
                        .HasConstraintName("FK__TheClass__IdStag__32B6742D");

                    b.Navigation("IdBranchNavigation");

                    b.Navigation("IdSchoolNavigation");

                    b.Navigation("IdStageNavigation");
                });

            modelBuilder.Entity("SchoolSystem.Data.ApplicationUser", b =>
                {
                    b.Navigation("DirectorateManager");

                    b.Navigation("Menegar");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSystem.Data.Branch", b =>
                {
                    b.Navigation("TheClasses");
                });

            modelBuilder.Entity("SchoolSystem.Data.Directorate", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("SchoolSystem.Data.Gender", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("SchoolSystem.Data.Lectuer", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("StudentLectuerTeachers");

                    b.Navigation("TeacherLectuerClasses");
                });

            modelBuilder.Entity("SchoolSystem.Data.School", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("Lectuers");

                    b.Navigation("Menegars");

                    b.Navigation("StudentLectuerTeachers");

                    b.Navigation("Students");

                    b.Navigation("TeacherLectuerClasses");

                    b.Navigation("Teachers");

                    b.Navigation("TheClasses");
                });

            modelBuilder.Entity("SchoolSystem.Data.StageClass", b =>
                {
                    b.Navigation("Schools");

                    b.Navigation("TheClasses");
                });

            modelBuilder.Entity("SchoolSystem.Data.StatusSchool", b =>
                {
                    b.Navigation("Schools");
                });

            modelBuilder.Entity("SchoolSystem.Data.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("StudentLectuerTeachers");
                });

            modelBuilder.Entity("SchoolSystem.Data.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("StudentLectuerTeachers");

                    b.Navigation("TeacherLectuerClasses");
                });

            modelBuilder.Entity("SchoolSystem.Data.TheClass", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("StudentLectuerTeachers");

                    b.Navigation("Students");

                    b.Navigation("TeacherLectuerClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
